### ISSUE TITLE
Historical request timing out

### ISSUE THREAD

**Issue by JoMiguelSantos** [apiforfun/theforexapi#12]
Requesting `curl https://theforexapi.com/api/2021-07-01` times out. 
I've tried several other dates with the same result. No change was made to the API so I assume there's an issue with the server?
Curling latest returns a response so it appears specific to this endpoint.

**Comment by jamiemlee** [comment]
I am having the same issue

**Comment by ashwin31** [comment]
it is fixed

**Comment by coolfire1231** [comment]
fixed
