### ISSUE TITLE
API of getting latest exchange rate is not working

### ISSUE THREAD

**Issue by matt-mi** [apiforfun/theforexapi#13]
Thank you for providing such amazing API. Now seems like the API of getting latest exchange rate is not working properly as below

```
(.venv) ➜  ~ curl https://theforexapi.com/api/2022-08-05/
{"date":"2022-08-04","base":"EUR","rates":{"USD":1.0181,"JPY":135.81,"BGN":1.9558,"CZK":24.659,"DKK":7.4425,"GBP":0.84231,"HUF":395.98,"PLN":4.7233,"RON":4.9261,"SEK":10.374,"CHF":0.9765,"ISK":138.7,"NOK":9.9065,"HRK":7.515,"TRY":18.2922,"AUD":1.4607,"BRL":5.3614,"CAD":1.307,"CNY":6.8769,"HKD":7.9919,"IDR":15200.94,"INR":80.7715,"KRW":1333.7,"MXN":20.756,"MYR":4.5387,"NZD":1.6172,"PHP":56.633,"SGD":1.4037,"THB":36.606,"ZAR":17.0352}}%
(.venv) ➜  ~ curl https://theforexapi.com/api/latest
a%
```

Would you please get it fixed soon? Thanks a lot

**Comment by ulassahillioglu** [comment]
I've been having issues for a couple hours either. Keeps throwing JSON Decode Error and RatesNotAvailableError. Also, when I open "https://theforexapi.com/api/", returns a page with some plain text. Something is wrong, I guess

**Comment by Ismail98np** [comment]
Again thank you so much for providing this api, but ive been having the same problem as the others for the past 24 hours too, the response that i am getting is only a letter 'a'.

**Comment by matt-mi** [comment]
I think the issue has been resolved and the API can return correct result now. Appreciate for prompt response on it, I'm closing the issue, thanks again!

**Comment by matt-mi** [comment]
I think the issue has been resolved and the API can return correct results now. Appreciate for prompt response on it, I'm closing the issue
